import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout'
import Image from 'next/image'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'

// import { Box, Button, Container, Grid, Heading, Text, Link } from "@chakra-ui/react";

import kalderHero from "../public/kalder-hero.png";
import kalderMobile from "../public/kalder-mobile.png";
import kalderLogo from "../public/kalder-logo.png";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Where communities become owners.
        </h1>

        <p className={styles.description}>
          Join communities, collect rewards. 
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Starface Silver &rarr;</h2>
            <p>Starface is a digital-first lifestyle brand that brings beauty and joy to every day rituals</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Adidas Ape Club &rarr;</h2>
            <p>Hill House Home is a digital-first lifestyle brand that brings beauty and joy to every day rituals.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Balenciagaverse &rarr;</h2>
            <p>Hill House Home is a digital-first lifestyle brand that brings beauty and joy to every day rituals.</p>
          </a>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home




// const Home: NextPage = () => {
//   return (
//     <Grid
//       backgroundColor="brand.border"
//       bottom={0}
//       gap="1px"
//       height="100%"
//       left={0}
//       minHeight="100vh"
//       overflow="hidden"
//       padding="1px"
//       position="absolute"
//       right={0}
//       templateColumns="1fr"
//       templateRows="75px 1fr"
//       top={0}
//     >
//       <Head>
//         <title>Kalder</title>
//         <meta name="description" content="Kalder" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Box display="flex" padding="19px 32px">
//         <Image height={37} src={kalderLogo} layout="fixed" width={197} />
//         <Button>Manifesto</Button>
//         <Button>About</Button>
//         <Box flex={1} />
//         <Button><Link href='login'>Log In</Link></Button>
//         <Button>Sign Up</Button>
//       </Box>
//       <Container maxW="6xl">
//         <Box alignItems="center" display="flex" height="100%">
//           <Box flex={1}>
//             <Heading>Mobilize Communities</Heading>
//             <Text>
//               A unified platform for brands and creators to launch tokenized
//               communities with tiered NFT membership cards, quests and beyond.
//             </Text>
//             <Text>
//               Sign up to build digital economies to where communities build
//               ownership and fandom.
//             </Text>
//             <Button
//               backgroundColor="brand.button"
//               color="white"
//               variant="solid"
//             >
//               Build a New World
//             </Button>
//           </Box>
//           <Box flex={1}>
//             <Image src={kalderMobile} />
//             <Image src={kalderHero} />
//           </Box>
//         </Box>
//       </Container>
//     </Grid>
//   );
// };

// export default Home;
