version: 3
endpoint: https://saved-lioness-66.hasura.app
admin_secret: 7nQfd17f6HxYtv1D8i7D7FRlRiYxS7rroVCoJHPColo12Y5ExDKfwtvva3uSeq9a
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
